export const menuButtons = [
    {
        text: "File",
        x: 20, y: 25,
    },
    {
        text: "Options",
        x: 80, y: 25,
    },
    {
        text: "Keno",
        x: 170, y: 25,
    },
    {
        text: "BANK",
        x: 20,
        y: 55,
    },
    {
        text: "CRAPS",
        x: 100,
        y: 295,
    },
    {
        text: "POKER",
        x: 360,
        y: 295,
    },
    {
        text: "SLOTS",
        x: 630,
        y: 295,
    },
    {
        text: "BLACKJACK",
        x: 80,
        y: 541,
    },
    {
        text: "ROULETTE",
        x: 350,
        y: 541,
    },
    {
        text: "BACCARAT",
        x: 610,
        y: 541,
    },

];

export const SOUNDS = [
    '6WAYAPPE',
    '6WAYGAME',
    'BACCARAT',
    'BALLHIT',
    'BALLHITR',
    'BALLROLL',
    'BET',
    'BLACKJACK',
    'CALL',
    'CARDFLIP',
    'CARDPLACE',
    'CARDSHUFFLE',
    'CHIPCHIP',
    'CHIPSTACK',
    'CHIPTABLE',
    'COINLAND',
    'CRAPSOPEN',
    'DIEFLOOR',
    'DIEONDIE',
    'DIESHAKE0',
    'DIESHAKE1',
    'DIESHAKE2',
    'DIESHAKE3',
    'DIESHAKE4',
    'DIESHAKE5',
    'DIESHAKE6',
    'DIESHAKE7',
    'DIESLIDE',
    'DIEWALLBOUNCE',
    'DRAWDOWN',
    'DRAWUP',
    'ERRORBEE',
    'FOLD',
    'INSERT10',
    'INSERT25',
    'KENOBELL',
    'KENOOPEN',
    'KENOWIN',
    'LOSTALL',
    'POKEROPEN',
    'PUCKAPPE',
    'PUCKREMO',
    'RAISE',
    'REELSTOP',
    'ROULETTE',
    'ROULETTESTOP',
    'SILENCE',
    'SLOTBELL',
    'SLOTSIREN',
    'SLOTSIREN2',
    'STAND',
    'WHOOSHFA',
];

export const navbarOptions = menuButtons.slice(0, 3);
