var GAMBLER_NAME = "";
var BANK_BALANCE = 0;
var STAKE = 0;

var BACCARAT_COMMISSION_OWED = 0;
var CRAPS_SHOOTER_INDEX = 0;
var POKER_DEALER_INDEX = 0;
var POKER_SETTINGS = {};
var KENO_COUNTDOWN_TEXT = "";
var TEST = true;
